services:
  menukitchen-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menukitchen-frontend
    restart: unless-stopped
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://217.76.53.136:3000
      - PORT=3000
    networks:
      - menukitchen-network

networks:
  menukitchen-network:
    driver: bridge
